# Generated by Django 3.2.5 on 2021-08-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
